In [5]:
class Employee:
    empCount=0
    salSum=0 
    def __init__(self,name,family,salary,department):
        self.name = name
        self.family = family
        self.salary = salary
        self.department = department
        Employee.empCount += 1
        Employee.salSum+=self.salary
    def avg(self):
        return Employee.salSum/Employee.empCount
    def displayCount(self): 
        print ("Total Employee %d" % Employee.empCount)
    def displayEmployee(self):
        print("Name : ", self.name, "Family: ", self.family , "Salary: ", self.salary, "department:",self.department)

emp1 = Employee("Teja Sai","Jammala",3000,"software")
emp2 = Employee("Sai","Charan",5000,"fatbee")
print("avg:",emp2.avg())
class FulltimeEmployee(Employee):
    def __init__(self,name,family,salary,department,c_name):
        super().__init__(name,family,salary,department)
        self.c_name=c_name
    def setCompany(self,c_name):
        self.c_name=c_name
    def getCompany(self):
        if self.c_name not in self.c_name:
            return ""
        return self.c_name
upen=FulltimeEmployee("Upender","Chitla",6000,"Front-end","JP Morgan")
upen.setCompany("Meta")
upen.getCompany(),upen.displayEmployee(),emp1.displayCount()

avg: 4000.0
Name :  Upender Family:  Chitla Salary:  6000 department: Front-end
Total Employee 3


('Meta', None, None)

In [2]:
import numpy as np 
vec=np.arange(1,21,dtype=float) 
print(vec)
vec=vec.reshape(4,5)
print(vec)
vec=np.where(np.isin(vec,vec.max(axis=1)),0,vec)
vec

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.
 19. 20.]
[[ 1.  2.  3.  4.  5.]
 [ 6.  7.  8.  9. 10.]
 [11. 12. 13. 14. 15.]
 [16. 17. 18. 19. 20.]]


array([[ 1.,  2.,  3.,  4.,  0.],
       [ 6.,  7.,  8.,  9.,  0.],
       [11., 12., 13., 14.,  0.],
       [16., 17., 18., 19.,  0.]])